# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load
ZSH_THEME="pygmalion"

# Add wisely, as too many plugins slow down shell startup.
plugins=(git colored-man colorize pip python brew osx zsh-syntax-highlighting)

# User Configuration
source $ZSH/oh-my-zsh.sh

source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# pyenv
eval "$(pyenv init -)"

# Add commonly used folders to $PATH
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Specify default editor. Possible values: vim, nano, ed etc.
export EDITOR=vim

# Add ~/bin to PATH
export PATH=$HOME/bin:$PATH

# Add sbin to PATH
export PATH=/usr/local/sbin:$PATH

# Add .local/bin to PATH
export PATH=$HOME/.local/bin:$PATH

# Add rbenv shim to PATH
export PATH="$HOME/.rbenv/bin:$PATH"

# Required rbenv eval
eval "$(rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/shawn.sichak/bin/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/shawn.sichak/bin/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/shawn.sichak/bin/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/shawn.sichak/bin/google-cloud-sdk/completion.zsh.inc'; fi
