# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Powerlevel10k
source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Add wisely, as too many plugins slow down shell startup.
plugins=(git colorize pip python brew osx)

### Fix slowness of pastes with zsh-syntax-highlighting.zsh
pasteinit() {
  OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
  zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
}

pastefinish() {
  zle -N self-insert $OLD_SELF_INSERT
}
zstyle :bracketed-paste-magic paste-init pasteinit
zstyle :bracketed-paste-magic paste-finish pastefinish
### Fix slowness of pastes

# User Configuration
source $ZSH/oh-my-zsh.sh
source $HOME/.zsh/zsh-autosuggestions.zsh
source $HOME/.zsh/zsh-syntax-highlighting.zsh

# Add commonly used folders to $PATH
export PATH="/usr/local/bin:/usr/local:/usr/bin:/bin:/usr/sbin:/sbin"

# Specify default editor. Possible values: vim, nano, ed etc.
export EDITOR=vim

# Add ~/bin to PATH
export PATH=$HOME/bin:$PATH

# Add sbin to PATH
export PATH=/usr/local/sbin:$PATH

# Add .local/bin to PATH
export PATH=$HOME/.local/bin:$PATH

# Add rbenv shim to PATH
export PATH="$HOME/.rbenv/bin:$PATH"

# Add binutils to PATH
export PATH="/usr/local/opt/binutils/bin:$PATH"

# Required rbenv eval
if command -v rbenv 1>/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

# Required pyenv eval
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

# Golang
export GOPATH="$HOME/code"
export PATH="$PATH:$GOPATH/bin"
export GO111MODULE=on

# Yubikey SSH
export SSH_AUTH_SOCK=$HOME/.gnupg/S.gpg-agent.ssh

# Load custom aliases
if [ -f ~/.zsh/zshalias ]; then
    source ~/.zsh/zshalias
fi
